.TH IGDEBI "1" "December 2017" "igdebi 0.1" "User Commands"
.SH NAME
igdebi \- install debian package from url
.SH SYNOPSIS
.B igdebi
[\fIURL \fR...]
.SH DESCRIPTION
Online debian package installer.
.PP
Download and install debian package from url or file path
.SH "SEE ALSO"
/usr/share/doc/python-igdebi-doc/index.html
.SH AUTHOR
igdebi module was written by Vítězslav Dvořák <info@vitexsoftware.cz>
.PP
This manual page was written by Vítězslav Dvořák <info@vitexsoftware.cz>,
for the Debian project (but may be used by others).
